#+title: Cooking Guide
** Mise-en-place and Meal Prep Principles
- My favorite tools
   - Cooking pots: Carbon Steel wok, Stainless steel pot with steamer layers, enameled cast iron pot for soups and roasts.
   - Cooking Tools: Chinese cleaver, Wood cutting board, Stir fry stainless steel spatula, boullion strainer/wire skimmmer, microwaveable stainless steel prep bowls, microwaveable stainless steel lunch box, tongs/chopsticks.
- Cooking with Chris has a lot of practical advice on simple, quick, healthy meal planning: [[https://x.com/coookwithchris/status/1919744081611125031][Busy Person Meal Plan]] and [[https://x.com/coookwithchris/status/1908851889950581166][Meal Prep]]. Long story short, cook some lean protein/fattier proteins, have some basic carbs, and roasted vegetables or microgreens as vegetables.

** Cooking Technique 
- Eggs:   [[https://www.youtube.com/watch?v=ONYflj0I2QI][Chinese Cooking Demystified]] is a great start for a method. The key is to not burn it, and adequate oil is helpful tool. Get good at scrambling and building a basic omlette. Get pasture-raised eggs if you can. I like to make a quick omlette with baby tomatoes, chinese sausages, green onions, and egg whites mixed with one or two whole eggs. 
- Fried rice [[https://www.youtube.com/watch?v=owUiKyx4chI][Stop Overthinking Fried Rice]] is a great tutorial on basics (and making rice itself is a technique [[https://www.youtube.com/watch?v=XjHQoYAp9I0][link]])

** Medicine and Health
- "Let food be thy medicine and medicine be thy food" - Hippocrates

- "A great cause of illness nowadays is the amount of medicine which fellows dose themselves with when there is no reason for taking any medicine at all. The best medicine is open-air and exercise and a big cup of water in the early morning if you are constipated, and a pint of hot water on going to bed."  - Baden Powell

- "That the ancients reduced medicine to physics or natural philosophy is evident both from name and thing. Hippocrates – the great master of medicinal wisdom – styles medicine φμάθησιν εμφυσιωθείσην: the natural science. And indeed there seems to be such an essential connection between medicine and natural philosophy as that they cannot, without violence offered to both, be disjoined from each other; which Aristotle and others acknowledge, whence it is that those great philosophers – Plato, Aristotle, and Theophrastus, with others – mix so many medicinal aphorisms with their natural philosophemes. Hence also, says Apuleius (Apology): “Let men cease to wonder, if the philosophers have in their very doctrine discoursed of the causes and remedies of diseases.” - [[https://static1.squarespace.com/static/651f101864aa9b577105268c/t/66927823baa5432de62fc48a/1720875043665/Health+Guide+of+the+Ancients_+Gale%27s+Microcosm.pdf%29][Theophilus Gale]]

- Note: Grow your soil! by Miessler is a good on gardening/soil health principles. Some theorize that there is a rapid degredation of soil quality in modern life, which affects the nutritional quality of plants and the meat that we eat. Based on this, I think we probably we need to supplement some nutrients (I take magnesium glycinate to improve my sleep quality). 

** Exercise and Health

-  "Fifty years ago, Mr. Catlin in America wrote a book called "Shut your mouth and save your life," and he showed how the [Native Americans of the United States] for a long time had adopted that method with their children to the extent of tying up their jaws at night to ensure their only breathing through their nose. Breathing through the nose prevents germs of disease getting from the air into the throat and stomach, it also prevents a growth in the back of the throat called "adenoids" which are apt to stop the breathing power of the nostrils, and also to cause deafness. For a scout nose-breathing is also specially useful.By keeping the mouth shut you prevent yourself from getting thirsty when you are doing hard work. And also at night if you are in the habit of breathing through the nose it prevents snoring, and snoring is a dangerous thing if you are sleeping anywhere in an enemy's country. Therefore practise keeping your mouth shut and breathing through your nose at all times." -  Baden Powell 

- "By practising your eyes in looking at things at a great distance they will grow stronger. While you are young you should save your eyes as much as possible, or they are not strong when you get older: therefore avoid reading by lamplight as much as possible and also sit with your back or side to the light when doing any work during the day; if you sit facing the light it strains your eyes." -  Baden Powell

- "Deep breathing is of the greatest importance for bringing fresh air into the lungs to be put into the blood, and for developing the size of the chest, but it should be done carefully, according to instructions, and not overdone, otherwise it is liable to strain the heart. The [Japanese] always carry on deep breathing exercise for a few minutes when they first get up in the morning, and always in the open air. It is done by sucking air in through the nose until it swells out your ribs as far as possible, especially at the back; then, after a pause, you breathe out the air slowly and gradually through the mouth until you have not a scrap of air left in you, then after a pause draw in your breath again through the nose as before." -  Baden Powell

- Great exercise routine: [[https://x.com/brettboettcher1/status/1940023935635984705][Sprint/Slow Jog, Bulgarian Split Squat, Dead hangs, Incline Dumbbell Chest Press, Weighted Chin up, Side Plank, Chest Supported Row, Single Leg Deadlift]]


