* Video Tutorials

* Health / Nutrition
** Medicine 
"Let food be thy medicine and medicine be thy food" - Hippocrates

"A great cause of illness nowadays is the amount of medicine which fellows dose themselves with when there is no reason for taking any medicine at all. The best medicine is open-air and exercise and a big cup of water in the early morning if you are constipated, and a pint of hot water on going to bed."  - Baden Powell

"That the ancients reduced medicine to physics or natural philosophy is evident both from name and thing. Hippocrates – the great master of medicinal wisdom – styles medicine φμάθησιν εμφυσιωθείσην: the natural science. And indeed there seems to be such an essential connection between medicine and natural philosophy as that they cannot, without violence offered to both, be disjoined from each other; which Aristotle and others acknowledge, whence it is that those great philosophers – Plato, Aristotle, and Theophrastus, with others – mix so many medicinal aphorisms with their natural philosophemes. Hence also, says Apuleius (Apology): “Let men cease to wonder, if the philosophers have in their very doctrine discoursed of the causes and remedies of diseases.” - Theophilus Gale (Court of the Gentiles) 

** Exercise

  "Fifty years ago, Mr. Catlin in America wrote a book called "Shut your mouth and save your life," and he showed how the Red Indians for a long time had adopted that method with their children to the extent of tying up their jaws at night to ensure their only breathing through their nose.
Breathing through the nose prevents germs of disease getting from the air into the throat and stomach, it also prevents a growth in the back of the throat called "adenoids" which are apt to stop the breathing power of the nostrils, and also to cause deafness. For a scout nose-breathing is also specially useful.By keeping the mouth shut you prevent yourself from getting thirsty when you are doing hard work. And also at night if you are in the habit of breathing through the nose it prevents snoring, and snoring is a dangerous thing if you are sleeping anywhere in an enemy's country. Therefore practise keeping your mouth shut and breathing through your nose at all times." -  Baden Powell 

"By practising your eyes in looking at things at a great distance they will grow stronger. While you are young you should save your eyes as much as possible, or they are not strong when you get older: therefore avoid reading by lamplight as much as possible and also sit with your back or side to the light when doing any work during the day; if you sit facing the light it strains your eyes." -  Baden Powell

"Deep breathing is of the greatest importance for bringing fresh air into the lungs to be put into the blood, and for developing the size of the chest, but it should be done carefully, according to instructions, and not overdone, otherwise it is liable to strain the heart. The [Japanese] always carry on deep breathing exercise for a few minutes when they first get up in the morning, and always in the open air. It is done by sucking air in through the nose until it swells out your ribs as far as possible, especially at the back; then, after a pause, you breathe out the air slowly and gradually through the mouth until you have not a scrap of air left in you, then after a pause draw in your breath again through the nose as before." -  Baden Powell
