* Video Tutorials

* Health / Nutrition

"Let food be thy medicine and medicine be thy food" - Hippocrates

"A great cause of illness nowadays is the amount of medicine which fellows dose themselves with when there is no reason for taking any medicine at all. The best medicine is open-air and exercise and a big cup of water in the early morning if you are constipated, and a pint of hot water on going to bed."  - Baden Powell

That the ancients reduced medicine to physics or natural philosophy is evident both from name and thing. Hippocrates – the great master of medicinal wisdom – styles medicine φμάθησιν εμφυσιωθείσην: the natural science. And indeed there seems to be such an essential connection between medicine and natural philosophy as that they cannot, without violence offered to both, be disjoined from each other; which Aristotle and others acknowledge, whence it is that those great philosophers – Plato, Aristotle, and Theophrastus, with others – mix so many medicinal aphorisms with their natural philosophemes. Hence also, says Apuleius (Apology): “Let men cease to wonder, if the philosophers have in their very doctrine discoursed of the causes and remedies of diseases.” - Theophilus Gale (Court of the Gentiles) 
